### ISSUE TITLE
Baulking_functions issue

### ISSUE THREAD

**Issue by mnips** [CiwPython/Ciw#109]
There is some issue in Baulking only because if it is removed from params the program runs.
PROGRAM:-

```
import ciw
import os
import random
import numpy as np
import pandas as pd
def time_dependent_func(t):
    return np.random.normal(10,2)

def my_baulking_function(n):
    if n<10:
        return 0.0
    return 1.0

params = {
    'Arrival_distributions': {'Class 0': [['TimeDependent', lambda t : time_dependent_func(t)], 'NoArrivals', 'NoArrivals', 'NoArrivals']},
    'Number_of_nodes': 4,
    'Number_of_servers': [1, 1, 1, 1],
    'Queue_capacities': ['Inf', 'Inf', 'Inf','Inf'],
    'Number_of_classes': 1,
    'Service_distributions': {'Class 0': [['Deterministic', 5.0], ['Deterministic', 6.0 ], ['Lognormal', 15.0,5.0], ['Lognormal', 30.0,4.0]]},
    'Transition_matrices': {'Class 0': [[0.0, 1,0,0], [0, 0.0,1,0],[0,0,0,0.2],[0,0,0,0]]},
    'Baulking_functions': {'Class 0': [my_baulking_function]}
}

ciw.seed(1)
N=ciw.create_network(params)
Q=ciw.Simulation(N)
Q.simulate_until_max_time(100)
recs = Q.get_all_records()
df = pd.DataFrame(recs)
df.set_index('id_number', inplace=True)
df.sort_values(by=['arrival_date', 'node'], ascending=[True, True], inplace=True)
print(df)

print("Baulked dict")
print (Q.baulked_dict )

```

My stack trace is:-
Traceback (most recent call last):
  File "C:/Users/Priyansh Soni/Desktop/temp.py", line 27, in <module>
    Q=ciw.Simulation(N)
  File "C:\Python27\lib\site-packages\ciw\simulation.py", line 46, in __init__
    for i in range(network.number_of_nodes)]
  File "C:\Python27\lib\site-packages\ciw\node.py", line 48, in __init__
    self.simulation.network.number_of_classes)]
IndexError: list index out of range

**Comment by geraintpalmer** [comment]
Hi @mnips 

Your list of baulking functions needs to be of length `'Number_of_nodes'`. If there is no baulking at those nodes (there isn't in your case as you have no arrivals to those nodes), then you can specify `None`.

e.g. your parameters dictionary should look like:

```
params = {
    'Arrival_distributions': {'Class 0': [['TimeDependent', lambda t : time_dependent_func(t)], 'NoArrivals', 'NoArrivals', 'NoArrivals']},
    'Number_of_nodes': 4,
    'Number_of_servers': [1, 1, 1, 1],
    'Queue_capacities': ['Inf', 'Inf', 'Inf','Inf'],
    'Number_of_classes': 1,
    'Service_distributions': {'Class 0': [['Deterministic', 5.0], ['Deterministic', 6.0 ], ['Lognormal', 15.0,5.0], ['Lognormal', 30.0,4.0]]},
    'Transition_matrices': {'Class 0': [[0.0, 1,0,0], [0, 0.0,1,0],[0,0,0,0.2],[0,0,0,0]]},
    'Baulking_functions': {'Class 0': [my_baulking_function, None, None, None]}
}
```
